version: '3.4'

services:
  tiendaservicios.api.autor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

  tiendaservicios.api.libros:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5112:80"


  tiendaservicios.api.carritocompra:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Libros=http://tiendaservicios.api.libros
      - Services__Autor=http://tiendaservicios.api.autor
    ports:
      - "5020:80"


  tiendaservicios.api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Autor=http://tiendaservicios.api.gateway
    depends_on:
      - tiendaservicios.api.libros  
    ports:
      - "5026:80"

